### ISSUE TITLE
Add support for Response generation

### ISSUE THREAD

**Issue by axnsan12** [axnsan12/drf-swagger#6]
- [x] Automatic generation of responses from serializers where possible
- [x] Manual customization/override
- [x] Support for paginated response
- [x] Tests

**Comment by axnsan12** [comment]
Done in 003a58aea85edd9493d4c4cf6f318a49b78f982f.

**Comment by chgad** [comment]
I stumbled upon this issue when writing a view which is a POST view but does not create an instanc but is responsible for email sending. So in the Docs it's Response falsely states a Repsonse body, which in reality is empty. How would i override the default behavior of "serializer generated" Response ?

**Comment by axnsan12** [comment]
You would override the endpoint's responses using `swagger_auto_schema`. See the readthedocs page about customizing the generation process.

**Comment by elnappo** [comment]
Could you provide an example on how to override a response schema based on a response serializer within a `GenericAPIView` or an `GenericViewSet`?

**Comment by axnsan12** [comment]
See the documentation on readthedocs.

**Comment by chgad** [comment]
Well, totally didn't recognize this section. 

Thanks
